### ISSUE TITLE
React warning keys

### ISSUE THREAD

**Issue by bartonhammond** [getsiphon/siphon-youtube-video-browser#1]
<img width="344" alt="screen shot 2016-06-06 at 1 06 11 pm" src="https://cloud.githubusercontent.com/assets/1282364/15832372/850700d2-2be7-11e6-9d9d-6fe8afbe0ec2.png">

**Comment by bartonhammond** [comment]
<img width="327" alt="screen shot 2016-06-06 at 4 41 10 pm" src="https://cloud.githubusercontent.com/assets/1282364/15838777/83e5e858-2c05-11e6-9342-dcd7a614cc3d.png">

**Comment by bartonhammond** [comment]
To reproduce:



1. Create new project
2. Delete components/*
2. Delete *.js
3. Clone this project
4. Copy files from clone
5. ```npm install```
6. ```siphon develop```

**Comment by drpancake** [comment]
Hey Barton,

Thanks for reporting this. We'll get this fixed up soon.

**Comment by notapipe** [comment]
Fixed
